// app/components/modspage/ModCard.vue
<template>
	<NuxtLink :to="`/mods/${mod.mod_id}`" class="mod-card group">
		<img
			:src="`${config.public.apiUrl}${mod.thumbnail}`"
			alt="mod image"
			class="w-24 h-24 rounded-xl object-contain shadow-2xl bg-white/5 p-2 group-hover:scale-105 transition-transform duration-200"
		>

		<div class="flex flex-col gap-2 flex-1">
			<div>
				<h3 class="text-xl text-white break-words font-bold group-hover:text-primary transition-colors">
					{{ mod.mod_name }}
				</h3>
				<span class="text-sm text-white/70">
					by {{ mod.author }}
				</span>
			</div>

			<div class="flex flex-wrap items-center gap-3 text-white/60 text-sm">
				<div class="flex items-center gap-1">
					<UIcon
						name="material-symbols:download"
						class="size-4"
					/>
					<span>{{ formatNumber(mod.downloads ?? 0) }} downloads</span>
				</div>
				<div class="flex items-center gap-1">
					<UIcon
						name="material-symbols:sync-outline"
						class="size-4"
					/>
					<span>Updated {{ formatTimeAgo(mod.updated_at ?? mod.created_at) }}</span>
				</div>
			</div>

			<p class="text-white/80 text-sm break-words line-clamp-2">
				{{ mod.description || "No description available." }}
			</p>
		</div>
	</NuxtLink>
</template>

<script setup lang="ts">
	import type { Mod } from "~/types";

	defineProps<{
		mod: Mod
	}>();

	const config = useRuntimeConfig();

	const formatNumber = (num: number) => {
		if (num >= 1000000) {
			return `${(num / 1000000).toFixed(1)}M`;
		} else if (num >= 1000) {
			return `${(num / 1000).toFixed(1)}K`;
		}
		return num.toString();
	};

	const formatTimeAgo = (dateInput: string | number | Date | undefined | null) => {
		if (dateInput === undefined || dateInput === null) {
			return "unknown";
		}

		let date: Date;

		if (dateInput instanceof Date) {
			date = dateInput;
		} else if (typeof dateInput === "number") {
			date = new Date(dateInput);
		} else {
			const trimmed = dateInput.trim();
			const asNumber = Number(trimmed);

			date = Number.isFinite(asNumber) ? new Date(asNumber) : new Date(trimmed);
		}

		if (Number.isNaN(date.getTime())) {
			return "unknown";
		}

		const now = new Date();
		const diffInMs = now.getTime() - date.getTime();
		const diffInDays = Math.floor(diffInMs / (1000 * 60 * 60 * 24));

		if (diffInDays === 0) {
			return "today";
		} else if (diffInDays === 1) {
			return "1 day ago";
		} else if (diffInDays < 7) {
			return `${diffInDays} days ago`;
		} else {
			return date.toLocaleDateString("en-US", {
				year: "numeric",
				month: "short",
				day: "numeric"
			});
		}
	};
</script>

// src/lib/features/mods/components/ModCard.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card';
	import { ImageOff, Download, Clock } from '@jis3r/icons';
	import type { Mod } from '$lib/features/mods/schema';

	let { mod }: { mod: Mod } = $props();
</script>

<Card.Root class="overflow-hidden p-0 transition-colors hover:bg-accent/50">
	<div class="flex h-40">
		<div class="h-40 w-40 flex-none shrink-0 bg-muted">
			{#if mod._links.thumbnail}
				<img src={mod._links.thumbnail} alt={mod.name} class="h-full w-full object-contain" />
			{:else}
				<div class="flex h-full w-full items-center justify-center">
					<ImageOff class="h-10 w-10 text-muted-foreground/40" />
				</div>
			{/if}
		</div>

		<div class="flex min-w-0 flex-1 flex-col p-3">
			<div class="min-w-0 flex-1">
				<h3 class="mb-0.5 truncate text-base leading-tight font-bold" title={mod.name}>
					{mod.name}
				</h3>
				<p class="mb-2 truncate text-sm text-muted-foreground/80">
					by {mod.author}
				</p>
				<p class="line-clamp-3 text-sm leading-snug text-muted-foreground">
					{mod.description}
				</p>
			</div>

			<div class="flex items-center gap-4 pt-2 text-sm font-medium">
				<div class="flex items-center gap-1.5">
					<Download class="text-primary" />
					<span>{mod.downloads.toLocaleString()}</span>
				</div>
				<div class="flex items-center gap-1.5 text-muted-foreground">
					<Clock />
					<span>{new Date(mod.updated_at).toLocaleDateString()}</span>
				</div>
			</div>
		</div>
	</div>
</Card.Root>
